### ISSUE TITLE
Publish on Accrescent store

### ISSUE THREAD

**Issue by shuvashish76** [SlaVcE14/JsonList#30]
Would you please consider publishing it on [Accrescent](https://github.com/accrescent/accrescent); an alternative android app store?

See their guide: https://accrescent.app/docs/guide/getting-started/

**Comment by SlaVcE14** [comment]
Sure, I would like to publish my app to as many app stores I could

**Comment by shuvashish76** [comment]
The project is still in alpha phase, you can contact them on [Matrix](https://matrix.to/#/#accrescent:matrix.org), if you've any queries.

**Comment by SlaVcE14** [comment]
For now, I will stick with F-Droid and IzzyOnDroid. Maybe later I will consider adding to that app store.
